
obrazy = {
    wojewodztwa_flagi: {
        "dolnośląskie": "../img/dolnoslaskie-f.svg",
        "kujawsko-pomorskie": "../img/kujawskopomorskie-f.svg",
        "lubelskie": "../img/lubelskie-f.svg",
        "lubuskie": "../img/lubuskie-f.svg",
        "łódzkie": "../img/lodzkie-f.svg",
        "małopolskie": "../img/malopolskie-f.svg",
        "mazowieckie": "../img/mazowieckie-f.svg",
        "opolskie": "../img/opolskie-f.svg",
        "podkarpackie": "../img/podkarpackie-f.svg",
        "podlaskie": "../img/podlaskie-f.svg",
        "pomorskie": "../img/pomorskie-f.svg",
        "śląskie": "../img/slaskie-f.svg",
        "świętokrzyskie": "../img/swietokrzyskie-f.svg",
        "warmińsko-mazurskie": "../img/warminskomazurskie-f.svg",
        "wielkopolskie": "../img/wielkopolskie-f.svg",
        "zachodniopomorskie": "../img/zachodniopomorskie-f.svg"
    },
    wojewodztwa_godla: {
        "dolnośląskie": "../img/dolnoslaskie-g.svg",
        "kujawsko-pomorskie": "../img/kujawskopomorskie-g.svg",
        "lubelskie": "../img/lubelskie-g.svg",
        "lubuskie": "../img/lubuskie-g.svg",
        "łódzkie": "../img/lodzkie-g.svg",
        "małopolskie": "../img/malopolskie-g.svg",
        "mazowieckie": "../img/mazowieckie-g.svg",
        "opolskie": "../img/opolskie-g.svg",
        "podkarpackie": "../img/podkarpackie-g.svg",
        "podlaskie": "../img/podlaskie-g.svg",
        "pomorskie": "../img/pomorskie-g.svg",
        "śląskie": "../img/slaskie-g.svg",
        "świętokrzyskie": "../img/swietokrzyskie-g.svg",
        "warmińsko-mazurskie": "../img/warminskomazurskie-g.svg",
        "wielkopolskie": "../img/wielkopolskie-g.svg",
        "zachodniopomorskie": "../img/zachodniopomorskie-g.svg"
    },
    europa_flagi: {
        "albania": "../img/albania.svg",
        "andora": "../img/andora.svg",
        "austria": "../img/austria.svg",
        "belgia": "../img/belgia.svg",
        "białoruś": "../img/białoruś.svg",
        "bośnia i hercegowina": "../img/bośnia i hercegowina.svg",
        "bułgaria": "../img/bułgaria.svg",
        "chorwacja": "../img/chorwacja.svg",
        "czarnogóra": "../img/czarnogóra.svg",
        "czechy": "../img/czechy.svg",
        "dania": "../img/dania.svg",
        "estonia": "../img/estonia.svg",
        "finlandia": "../img/finlandia.svg",
        "francja": "../img/francja.svg",
        "grecja": "../img/grecja.svg",
        "hiszpania": "../img/hiszpania.svg",
        "holandia": "../img/holandia.svg",
        "irlandia": "../img/irlandia.svg",
        "islandia": "../img/islandia.svg",
        "kazachstan": "../img/kazachstan.svg",
        "liechtenstein": "../img/liechtenstein.svg",
        "litwa": "../img/litwa.svg",
        "luksemburg": "../img/luksemburg.svg",
        "łotwa": "../img/łotwa.svg",
        "macedonia północna": "../img/macedonia północna.svg",
        "malta": "../img/malta.svg",
        "mołdawia": "../img/mołdawia.svg",
        "monako": "../img/monako.svg",
        "niemcy": "../img/niemcy.svg",
        "norwegia": "../img/norwegia.svg",
        "polska": "../img/polska.svg",
        "portugalia": "../img/portugalia.svg",
        "rosja": "../img/rosja.svg",
        "rumunia": "../img/rumunia.svg",
        "san marino": "../img/san marino.svg",
        "serbia": "../img/serbia.svg",
        "słowacja": "../img/słowacja.svg",
        "słowenia": "../img/słowenia.svg",
        "szwajcaria": "../img/szwajcaria.svg",
        "szwecja": "../img/szwecja.svg",
        "turcja": "../img/turcja.svg",
        "ukraina": "../img/ukraina.svg",
        "watykan": "../img/watykan.svg",
        "węgry": "../img/węgry.svg",
        "wielka brytania": "../img/wielka brytania.svg",
        "włochy": "../img/włochy.svg",
        "azerbejdżan": "../img/azerbejdżan.svg",
        "kosowo": "../img/kosowo.svg",
        "gruzja": "../img/gruzja.svg"
    }
}